[build]
  command = "yarn generate"
  publish = "dist/"

[functions]
  directory = "functions"

[[redirects]]
  from = "/movies/*"
  to = "/.netlify/functions/render"
  status = 200

[[plugins]]
  package = "/netlify-plugins/copy-build-artifacts"